/*
      1) Install Courier SDK: npm install @trycourier/courier
      2) Make sure you allow ES module imports: Add "type": "module" to package.json file
      */
      import { CourierClient } from "@trycourier/courier";

      const courier = CourierClient(
        { authorizationToken: "pk_prod_17HYZ9N4X6MH40PNPRVZVR5XEKQ9"});

      const { requestId } = await courier.send({
        message: {
          to: {
            phone_number: "254796250508"
          },
          content: {
            title: "Welcome to Courier!",
            body: "Want to hear a joke? {{joke}}"
          },
          data: {
            joke: "Why was the JavaScript developer sad? Because they didn't Node how to Express themselves"
          },
        }
      });